server:
  port: 8079
  servlet:
    context-path: /api
    encoding:
      force: true
spring:
  application:
    name: payments-api
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/payments
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
springdoc:
  swagger-ui:
    disable-swagger-default-url: false
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    enabled: true
swagger-servers-urls: http://localhost:${server.port}${server.servlet.context-path},http://127.0.0.1:${server.port}${server.servlet.context-path}

feign:
  client:
    config:
      order-api:
        service:
          url: http://localhost:8078/api/v1

aws:
  queues:
    Region: "sa-east-1"
    Endpoint: http://localhost:4566
    PaymentEventsQueue: "PaymentEvents"
    OrderEventsQueue: "OrderEvents"