name: Code Coverage

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install test jacoco:report

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          args:
            -Dsonar.projectKey=tech-challenge-fiap-5soat_tc-ff-payments-api
            -Dsonar.organization=tech-challenge-fiap-5soat

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Generate Coverage Report
#        run: |
#          mvn -B package --file pom.xml jacoco:report
#
#      - name: Upload Report
#        uses: 'actions/upload-artifact@v2'
#        with:
#          name: jacoco-report
#          path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
#
#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.2
#        with:
#          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 80
#          min-coverage-changed-files: 80
#          title: Code Coverage
#
#      - name: Save Coverage To Environment Variable
#        run: |
#          echo "TOTAL_COVERAGE=${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_ENV
#          echo "CHANGED_FILES_COVERAGE=${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_ENV
#
#  sonarcloud:
#    runs-on: ubuntu-latest
#    needs: test
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: '1.21'
#
#      - name: Download coverage report
#        uses: actions/download-artifact@v3
#        with:
#          name: coverage-report
#          path: coverage
#
#      - name: List files (debugging step)
#        run: ls -la coverage
#
#      - name: Show sonar-propss
#        run: cat sonar-project.properties
#
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}